# Generated by Django 4.2 on 2023-04-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imageURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
